import type { AffirmationStyle, NarratorId } from '../types';

const ASSETS: Record<NarratorId, Record<string, number>> = {
  female: {
    'peace-prosperity-1:command': require('../../assets/affirmations/v1/female/peace-prosperity-1-command.mp3'),
    'peace-prosperity-1:becoming': require('../../assets/affirmations/v1/female/peace-prosperity-1-becoming.mp3'),
    'peace-prosperity-2:command': require('../../assets/affirmations/v1/female/peace-prosperity-2-command.mp3'),
    'peace-prosperity-2:becoming': require('../../assets/affirmations/v1/female/peace-prosperity-2-becoming.mp3'),
    'sleep-night-1:command': require('../../assets/affirmations/v1/female/sleep-night-1-command.mp3'),
    'sleep-night-1:becoming': require('../../assets/affirmations/v1/female/sleep-night-1-becoming.mp3'),
    'sleep-night-2:command': require('../../assets/affirmations/v1/female/sleep-night-2-command.mp3'),
    'sleep-night-2:becoming': require('../../assets/affirmations/v1/female/sleep-night-2-becoming.mp3'),
    'gratitude-1:command': require('../../assets/affirmations/v1/female/gratitude-1-command.mp3'),
    'gratitude-1:becoming': require('../../assets/affirmations/v1/female/gratitude-1-becoming.mp3'),
    'gratitude-2:command': require('../../assets/affirmations/v1/female/gratitude-2-command.mp3'),
    'gratitude-2:becoming': require('../../assets/affirmations/v1/female/gratitude-2-becoming.mp3'),
    'divine-rhythm-1:command': require('../../assets/affirmations/v1/female/divine-rhythm-1-command.mp3'),
    'divine-rhythm-1:becoming': require('../../assets/affirmations/v1/female/divine-rhythm-1-becoming.mp3'),
    'divine-rhythm-2:command': require('../../assets/affirmations/v1/female/divine-rhythm-2-command.mp3'),
    'divine-rhythm-2:becoming': require('../../assets/affirmations/v1/female/divine-rhythm-2-becoming.mp3'),
    'circulation-giving-1:command': require('../../assets/affirmations/v1/female/circulation-giving-1-command.mp3'),
    'circulation-giving-1:becoming': require('../../assets/affirmations/v1/female/circulation-giving-1-becoming.mp3'),
    'circulation-giving-2:command': require('../../assets/affirmations/v1/female/circulation-giving-2-command.mp3'),
    'circulation-giving-2:becoming': require('../../assets/affirmations/v1/female/circulation-giving-2-becoming.mp3'),
    'reflection-confidence-1:command': require('../../assets/affirmations/v1/female/reflection-confidence-1-command.mp3'),
    'reflection-confidence-1:becoming': require('../../assets/affirmations/v1/female/reflection-confidence-1-becoming.mp3'),
    'reflection-confidence-2:command': require('../../assets/affirmations/v1/female/reflection-confidence-2-command.mp3'),
    'reflection-confidence-2:becoming': require('../../assets/affirmations/v1/female/reflection-confidence-2-becoming.mp3'),
    'faith-certainty-1:command': require('../../assets/affirmations/v1/female/faith-certainty-1-command.mp3'),
    'faith-certainty-1:becoming': require('../../assets/affirmations/v1/female/faith-certainty-1-becoming.mp3'),
    'faith-certainty-2:command': require('../../assets/affirmations/v1/female/faith-certainty-2-command.mp3'),
    'faith-certainty-2:becoming': require('../../assets/affirmations/v1/female/faith-certainty-2-becoming.mp3'),
    'mastery-thought-1:command': require('../../assets/affirmations/v1/female/mastery-thought-1-command.mp3'),
    'mastery-thought-1:becoming': require('../../assets/affirmations/v1/female/mastery-thought-1-becoming.mp3'),
    'mastery-thought-2:command': require('../../assets/affirmations/v1/female/mastery-thought-2-command.mp3'),
    'mastery-thought-2:becoming': require('../../assets/affirmations/v1/female/mastery-thought-2-becoming.mp3'),
    'definite-aim-1:command': require('../../assets/affirmations/v1/female/definite-aim-1-command.mp3'),
    'definite-aim-1:becoming': require('../../assets/affirmations/v1/female/definite-aim-1-becoming.mp3'),
    'definite-aim-2:command': require('../../assets/affirmations/v1/female/definite-aim-2-command.mp3'),
    'definite-aim-2:becoming': require('../../assets/affirmations/v1/female/definite-aim-2-becoming.mp3'),
    'identity-1:command': require('../../assets/affirmations/v1/female/identity-1-command.mp3'),
    'identity-1:becoming': require('../../assets/affirmations/v1/female/identity-1-becoming.mp3'),
    'identity-2:command': require('../../assets/affirmations/v1/female/identity-2-command.mp3'),
    'identity-2:becoming': require('../../assets/affirmations/v1/female/identity-2-becoming.mp3'),
    'repetition-becoming-1:command': require('../../assets/affirmations/v1/female/repetition-becoming-1-command.mp3'),
    'repetition-becoming-1:becoming': require('../../assets/affirmations/v1/female/repetition-becoming-1-becoming.mp3'),
    'repetition-becoming-2:command': require('../../assets/affirmations/v1/female/repetition-becoming-2-command.mp3'),
    'repetition-becoming-2:becoming': require('../../assets/affirmations/v1/female/repetition-becoming-2-becoming.mp3'),
    'boldness-courage-1:command': require('../../assets/affirmations/v1/female/boldness-courage-1-command.mp3'),
    'boldness-courage-1:becoming': require('../../assets/affirmations/v1/female/boldness-courage-1-becoming.mp3'),
    'boldness-courage-2:command': require('../../assets/affirmations/v1/female/boldness-courage-2-command.mp3'),
    'boldness-courage-2:becoming': require('../../assets/affirmations/v1/female/boldness-courage-2-becoming.mp3'),
    'action-urgency-1:command': require('../../assets/affirmations/v1/female/action-urgency-1-command.mp3'),
    'action-urgency-1:becoming': require('../../assets/affirmations/v1/female/action-urgency-1-becoming.mp3'),
    'action-urgency-2:command': require('../../assets/affirmations/v1/female/action-urgency-2-command.mp3'),
    'action-urgency-2:becoming': require('../../assets/affirmations/v1/female/action-urgency-2-becoming.mp3'),
    'legacy-service-1:command': require('../../assets/affirmations/v1/female/legacy-service-1-command.mp3'),
    'legacy-service-1:becoming': require('../../assets/affirmations/v1/female/legacy-service-1-becoming.mp3'),
    'legacy-service-2:command': require('../../assets/affirmations/v1/female/legacy-service-2-command.mp3'),
    'legacy-service-2:becoming': require('../../assets/affirmations/v1/female/legacy-service-2-becoming.mp3'),
  },
  male: {
    'peace-prosperity-1:command': require('../../assets/affirmations/v1/male/peace-prosperity-1-command.mp3'),
    'peace-prosperity-1:becoming': require('../../assets/affirmations/v1/male/peace-prosperity-1-becoming.mp3'),
    'peace-prosperity-2:command': require('../../assets/affirmations/v1/male/peace-prosperity-2-command.mp3'),
    'peace-prosperity-2:becoming': require('../../assets/affirmations/v1/male/peace-prosperity-2-becoming.mp3'),
    'sleep-night-1:command': require('../../assets/affirmations/v1/male/sleep-night-1-command.mp3'),
    'sleep-night-1:becoming': require('../../assets/affirmations/v1/male/sleep-night-1-becoming.mp3'),
    'sleep-night-2:command': require('../../assets/affirmations/v1/male/sleep-night-2-command.mp3'),
    'sleep-night-2:becoming': require('../../assets/affirmations/v1/male/sleep-night-2-becoming.mp3'),
    'gratitude-1:command': require('../../assets/affirmations/v1/male/gratitude-1-command.mp3'),
    'gratitude-1:becoming': require('../../assets/affirmations/v1/male/gratitude-1-becoming.mp3'),
    'gratitude-2:command': require('../../assets/affirmations/v1/male/gratitude-2-command.mp3'),
    'gratitude-2:becoming': require('../../assets/affirmations/v1/male/gratitude-2-becoming.mp3'),
    'divine-rhythm-1:command': require('../../assets/affirmations/v1/male/divine-rhythm-1-command.mp3'),
    'divine-rhythm-1:becoming': require('../../assets/affirmations/v1/male/divine-rhythm-1-becoming.mp3'),
    'divine-rhythm-2:command': require('../../assets/affirmations/v1/male/divine-rhythm-2-command.mp3'),
    'divine-rhythm-2:becoming': require('../../assets/affirmations/v1/male/divine-rhythm-2-becoming.mp3'),
    'circulation-giving-1:command': require('../../assets/affirmations/v1/male/circulation-giving-1-command.mp3'),
    'circulation-giving-1:becoming': require('../../assets/affirmations/v1/male/circulation-giving-1-becoming.mp3'),
    'circulation-giving-2:command': require('../../assets/affirmations/v1/male/circulation-giving-2-command.mp3'),
    'circulation-giving-2:becoming': require('../../assets/affirmations/v1/male/circulation-giving-2-becoming.mp3'),
    'reflection-confidence-1:command': require('../../assets/affirmations/v1/male/reflection-confidence-1-command.mp3'),
    'reflection-confidence-1:becoming': require('../../assets/affirmations/v1/male/reflection-confidence-1-becoming.mp3'),
    'reflection-confidence-2:command': require('../../assets/affirmations/v1/male/reflection-confidence-2-command.mp3'),
    'reflection-confidence-2:becoming': require('../../assets/affirmations/v1/male/reflection-confidence-2-becoming.mp3'),
    'faith-certainty-1:command': require('../../assets/affirmations/v1/male/faith-certainty-1-command.mp3'),
    'faith-certainty-1:becoming': require('../../assets/affirmations/v1/male/faith-certainty-1-becoming.mp3'),
    'faith-certainty-2:command': require('../../assets/affirmations/v1/male/faith-certainty-2-command.mp3'),
    'faith-certainty-2:becoming': require('../../assets/affirmations/v1/male/faith-certainty-2-becoming.mp3'),
    'mastery-thought-1:command': require('../../assets/affirmations/v1/male/mastery-thought-1-command.mp3'),
    'mastery-thought-1:becoming': require('../../assets/affirmations/v1/male/mastery-thought-1-becoming.mp3'),
    'mastery-thought-2:command': require('../../assets/affirmations/v1/male/mastery-thought-2-command.mp3'),
    'mastery-thought-2:becoming': require('../../assets/affirmations/v1/male/mastery-thought-2-becoming.mp3'),
    'definite-aim-1:command': require('../../assets/affirmations/v1/male/definite-aim-1-command.mp3'),
    'definite-aim-1:becoming': require('../../assets/affirmations/v1/male/definite-aim-1-becoming.mp3'),
    'definite-aim-2:command': require('../../assets/affirmations/v1/male/definite-aim-2-command.mp3'),
    'definite-aim-2:becoming': require('../../assets/affirmations/v1/male/definite-aim-2-becoming.mp3'),
    'identity-1:command': require('../../assets/affirmations/v1/male/identity-1-command.mp3'),
    'identity-1:becoming': require('../../assets/affirmations/v1/male/identity-1-becoming.mp3'),
    'identity-2:command': require('../../assets/affirmations/v1/male/identity-2-command.mp3'),
    'identity-2:becoming': require('../../assets/affirmations/v1/male/identity-2-becoming.mp3'),
    'repetition-becoming-1:command': require('../../assets/affirmations/v1/male/repetition-becoming-1-command.mp3'),
    'repetition-becoming-1:becoming': require('../../assets/affirmations/v1/male/repetition-becoming-1-becoming.mp3'),
    'repetition-becoming-2:command': require('../../assets/affirmations/v1/male/repetition-becoming-2-command.mp3'),
    'repetition-becoming-2:becoming': require('../../assets/affirmations/v1/male/repetition-becoming-2-becoming.mp3'),
    'boldness-courage-1:command': require('../../assets/affirmations/v1/male/boldness-courage-1-command.mp3'),
    'boldness-courage-1:becoming': require('../../assets/affirmations/v1/male/boldness-courage-1-becoming.mp3'),
    'boldness-courage-2:command': require('../../assets/affirmations/v1/male/boldness-courage-2-command.mp3'),
    'boldness-courage-2:becoming': require('../../assets/affirmations/v1/male/boldness-courage-2-becoming.mp3'),
    'action-urgency-1:command': require('../../assets/affirmations/v1/male/action-urgency-1-command.mp3'),
    'action-urgency-1:becoming': require('../../assets/affirmations/v1/male/action-urgency-1-becoming.mp3'),
    'action-urgency-2:command': require('../../assets/affirmations/v1/male/action-urgency-2-command.mp3'),
    'action-urgency-2:becoming': require('../../assets/affirmations/v1/male/action-urgency-2-becoming.mp3'),
    'legacy-service-1:command': require('../../assets/affirmations/v1/male/legacy-service-1-command.mp3'),
    'legacy-service-1:becoming': require('../../assets/affirmations/v1/male/legacy-service-1-becoming.mp3'),
    'legacy-service-2:command': require('../../assets/affirmations/v1/male/legacy-service-2-command.mp3'),
    'legacy-service-2:becoming': require('../../assets/affirmations/v1/male/legacy-service-2-becoming.mp3'),
  },
};

export function resolveAffirmationAsset(affirmationId: string, style: AffirmationStyle, narratorId: NarratorId): number {
  const key = `${affirmationId}:${style}`;
  const source = ASSETS[narratorId]?.[key];
  if (!source) throw new Error(`Missing neural affirmation asset: ${narratorId}/${key}`);
  return source;
}

export const BUNDLED_AFFIRMATION_COUNT = 28;
